version: "2"
services:
  jupyter_notebook:
    image: jupyter/pyspark-notebook
    volumes:
      - ./code:/home/jovyan
    ports:
      - 8888:8888
    command: "start-notebook.sh \
        --NotebookApp.token='' \
        --NotebookApp.password=''"